apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
  name: react-app
  namespace: obf
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: react-app
  type: NodePort
